site_name: TC-48 Architecture Documentation
site_author: Maqix
docs_dir: src

theme:
  name: material
  features:
    - navigation.sections
    - navigation.expand
    - content.code.copy

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - md_in_html

extra_javascript:
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

nav:
  - Introduction: index.md
  - Memory:
      - Word Definitions: memory/words.md
      - Signed Integers: memory/signed-ints.md
      - Model: memory/model.md
  - ISA:
      - Instruction Encoding: isa/instruction-encoding.md
      - Instruction Set: isa/instruction-set.md
      - Registers: isa/registers.md
      - Flags: isa/flags.md
  - Instruction Set:
      - Arithmetic Operations: isa/instruction-set/arithmetic.md
      - Trit-Wise Operations: isa/instruction-set/trit-wise.md
      - Memory Operations: isa/instruction-set/memory-ops.md
      - Input/Output Operations: isa/instruction-set/input-output.md
      - Other Operations: isa/instruction-set/other.md
  - I/O System:
      - PMIO Model: io/pmio.md
      - Bus Controller: io/bus-controller.md
